FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags='-s -w' -o /scheduler ./cmd/server

FROM gcr.io/distroless/static
COPY --from=builder /scheduler /scheduler
ENTRYPOINT ["/scheduler"]
