name: Backend CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with: { go-version: '1.23' }
      - name: Test
        run: |
          go test ./... -coverprofile=coverage.out || true
          go tool cover -func=coverage.out | tee cov.txt
          awk '/total:/ {print $3}' cov.txt | grep -E '^100%$' || echo 'coverage <100% (adjust as needed)'
